#pragma once

#define ARGV_PROFILE "-profile"
#define ARGV_PROFILESDIR "-profilesdir"
#define ARGV_DEBUG "-debug"
#define ARGV_HELP "-?"
#define ARGV_LOGPATH "-logpath"
#define ARGV_PLUGINS "-plugins"
#define ARGV_RESTORE "-restore"
#define ARGV_OFFLINE "-offline"
#define ARGV_MAKEREPORT "-makeReport"
#define ARGV_NOCATCH "-nocatch"
#define ARGV_DEBUGALL "-debugall"
#define ARGV_STARTDEV "-startDev"
#define ARGV_TEST "-test"
